---
php_packages:
  - php5
  - libapache2-mod-php5
  - php5-mysql
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php-pear
  - php-apc
  - php5-json
  - libpcre3-dev
