---
php_packages:
  - php
  - php-devel
  - php-mysql
  - php-mcrypt
  - php-cli
  - php-common
  - php-curl
  - php-gd
  - php-pear
  - php-apc
  - php-json
  - pcre-devel
yum_repos:
  - http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
