---
- name: start apache
  service: name={{ apache_service }} state=started

- name: restart apache
  service: name={{ apache_service }} state=restarted

- name: reload apache
  service: name={{ apache_service }} state=reloaded

- name: enable apache
  service: name={{ apache_service }} state=started enabled=yes
