---
  - name: CONFIGURE | load variables for distro
    include_vars: "{{ ansible_os_family }}.yml"

  - include: RedHat.yml
    when: ansible_os_family == 'RedHat'

  - include: Debian.yml
    when: ansible_os_family == 'Debian'

  - name: CONFIG | generate apache site config
    template:
      src: vhost.config.j2
      dest: "{{ apache_sites_dir }}/{{ a2_siteconfig }}.conf"
      mode: 0644
    notify:
      - restart apache

  - name: SSL | copy ssl key
  
