---
  - name: YUM | install apache2 packages
    yum: name={{ item }} state=installed
    with_items: apache_pkgs
    notify:
      - restart apache
      - enable apache

  - name: FIREWALL | open http service port
    firewalld: service=http permanent=true state=enabled

  - service: name=firewalld state=restarted
