---
  - name: INSTALL | Download wordpress
    command: "wp core download --path={{ wp_dir }} --allow-root"

  - name: CONFIG | Configure wordpress
    command: "wp core config --allow-root --dbuser={{ wp_db_user }} --dbpass={{ wp_db_pass}} --dbname={{ wp_db_name}} --path={{ wp_dir }}"

  - name: INSTALL | Install Database Tables
    command: "wp core install --url={{ wp_url }} --title='{{ wp_title }}' --admin_user={{ wp_admin }} --admin_password={{ wp_admin_pw}} --admin_email={{ wp_admin_email }} --path={{ wp_dir }} --allow-root"

  - name: INSTALL | Install plugins
    command: "wp plugin install {{ item }} --activate --allow-root --path={{ wp_dir }}"
    with_items: "{{ wp_plugins }}"

  - name: INSTALL | Install themes
    command: "wp theme install {{ item }} --allow-root --path={{ wp_dir }}"
    with_items: "{{ wp_themes }}"

  - name: CONFIG | Activate theme
    command: "wp theme activate {{ wp_theme_active }} --allow-root --path={{ wp_dir }}"
    when: wp_theme_active|default(None) != None

  - name: CONFIG | set permalinks in wordpress
    command: "wp rewrite structure '/%year%/%monthnum%/%day%/%postname%/' --allow-root --path={{ wp_dir }}"
