---
# Install WP
- name: INSTALL | Creating install directory if not present
  file:
    path: "{{ wp_dir }}"
    state: directory

- stat: path=/user/bin/wp
  register: wp_cli

- name: INSTALL | Download wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/bin/wp
  when: wp_cli.stat.exists == False

- name: INSTALL | Set permissions on wp-cli
  file: path=/usr/bin/wp mode="0755"

# Register bool if site exists to signal install to skip.
- name: CONFIG | Determine if config file exists
  stat: "path={{ wp_dir }}/index.php"
  register: config_file

- include: install-wp.yml
  when: config_file.stat.exists == False

# Security Config
- name: WP | Change owner of wp directory to apache user.
  file:
    path: "{{ wp_dir }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: "{{ wp_app_user }}"
    group: "{{ wp_app_group }}"

# securit on config.php to 0644
- name: WP | Set permission on wp-config.php to 644
  file: path="{{ wp_dir }}/wp-config.php" mode=0644
