---
  - hosts: all
    user: vagrant
    sudo: yes
    vars:
      playbook_name: common-playbook
      ssh_users:
        - { name: 'tur057', keyfile: 'tur057_rsa.pub' }
      sudoers:
        - 'tur057'
      deleted_users:
        - 'ssh_users'
    roles:
      - common
