---
  - hosts: all
    user: tur057
    sudo: yes
    vars_files:
      - vars/{{ ansible_os_family }}.yml
      - secretvars/secretvars.yml
    vars:
      # Common vars
      playbook_name: "fire-playbook"
      ssh_users:
          - name: tur057
            keyfile: public_keys/scott.turnbull.henrico.id_rsa.pub
      sudoers:
        - tur057
      deleted_users:
        - streamweaver
      # Apache vars
      a2_documentroot: /opt/wordpress
      a2_aliases:
        - name: /wiki
          path: /opt/dokuwiki
      a2_directories:
        - name: /
          options:
            - Options FollowSymLinks
            - AllowOverride None
            - Require all denied
        - name: /opt/wordpress
          options:
              - Options FollowSymLinks MultiViews Includes ExecCGI
              - AllowOverride All
              - Order allow,deny
              - Allow from all
              - Require all granted
        - name: /opt/dokuwiki
          options:
            - Options Indexes FollowSymLinks MultiViews
            - AllowOverride None
            - Order allow,deny
            - allow from all
            - Require all granted
      a2_locationmatches:
        - name: "/(data|conf|bin|inc)/"
          options:
            - Order allow,deny
            - Deny from all
            - Satisfy All
      a2modules_active:
        - 'rewrite'
      # mysql vars
      mysql_root_db_pass: "{{ _mysql_root_db_pass }}"
      mysql_root_users:
        - name: root
          home: /root
        - name: tur057
          home: /home/tur057
      mysql_dbs:
        - wp_fireforms
      mysql_users:
        - name: wp_fireforms
          db: wp_fireforms
          pass: "{{ _wp_db_pass }}"
          priv: "wp_fireforms.*:ALL"
      # Wordpress Vars
      wp_db_user: wp_fireforms
      wp_dir: /opt/wordpress
      wp_db_name: wp_fireforms
      wp_db_pass: "{{ _wp_db_pass }}"
      wp_db_user: wp_fireforms
      wp_title: "Henrico Division of Fire"
      wp_url: http://uhfd783.govt.hcg.local
      wp_admin: wp_fireadmin
      wp_admin_pw: "{{ _wp_admin_pw }}"
      wp_admin_email: set@inplaybook.com
      wp_plugins:
        - ninja-forms
        - wpmandrill
        - active-directory-integration
      wp_themes:
        - wp-simple
      wp_theme_active: wp-simple
      wp_app_user: "{{ apache_user }}"
      wp_app_group: "{{ apache_user }}"
      # DokuWiki Vars
      dw_dir: /opt/dokuwiki
      dw_app_user: "{{ apache_user }}"
      dw_app_group: "{{ apache_user }}"
    roles:
      - common
      - php
      - apache2
      - mysql
      - wordpress
      - dokuwiki
