---
  - hosts: all
    user: vagrant
    sudo: yes
    vars_files:
      - vars/{{ ansible_os_family }}.yml
      - secretvars/secretvars.yml
    vars:
      # Common vars
      playbook_name: "utility_playbook"
      ssh_users:
          - name: streamweaver
            keyfile: public_keys/scott.turnbull.henrico.id_rsa.pub
      sudoers:
        - streamweaver
      deleted_users: None
      # Apache vars
      a2_documentroot: /opt/wordpress
      a2_directories:
        - name: /
          options:
            - Options FollowSymLinks
            - AllowOverride None
            - Require all denied
      a2_locationmatches:
        - name: "/(data|conf|bin|inc)/"
          options:
            - Order allow,deny
            - Deny from all
            - Satisfy All
      a2modules_active:
        - 'rewrite'
      # HTTPS Variables
      https_pem: ssl/uhfd783.pem
      https_documentroot: /opt/wordpress
      https_directories:
        - name: /opt/wordpress
          options:
              - Options FollowSymLinks MultiViews Includes ExecCGI
              - AllowOverride All
              - Order allow,deny
              - Allow from all
              - Require all granted
      # mysql vars
      mysql_root_db_pass: "{{ _mysql_root_db_pass }}"
      mysql_dbs:
        - wp_fireforms
      mysql_users:
        - name: wp_fireforms
          db: wp_fireforms
          pass: "{{ _wp_db_pass }}"
          priv: "wp_fireforms.*:ALL"
      # Wordpress Vars
      wp_db_user: wp_fireforms
      wp_dir: /opt/wordpress
      wp_db_name: wp_fireforms
      wp_db_pass: "{{ _wp_db_pass }}"
      wp_db_user: wp_fireforms
      wp_title: "Henrico Division of Fire"
      wp_url: http://192.168.33.10
      wp_admin: wp_fireadmin
      wp_admin_pw: "{{ _wp_admin_pw }}"
      wp_admin_email: set@inplaybook.com
      wp_plugins:
        - ninja-forms
        - wpmandrill
        - active-directory-integration
      wp_themes:
        - wp-simple
      wp_theme_active: wp-simple
      wp_app_user: "{{ apache_user }}"
      wp_app_group: "{{ apache_user }}"
      # DokuWiki Vars
      dw_dir: /opt/dokuwiki
      dw_app_user: "{{ apache_user }}"
      dw_app_group: "{{ apache_user }}"
    roles:
      - common
      - php
      - http
      - https
      - mysql
      - wordpress
