---
  - hosts: all
    user: vagrant
    sudo: yes
    vars_files:
      - vars/{{ ansible_os_family }}.yml
    vars:
      # Common vars
      playbook_name: utility-playbook
      ssh_users: None
      sudoers: None
      deleted_users: None
      # Apache vars
      a2_aliases:
        - name: /blog
          path: /opt/wordpress
        - name: /wiki
          path: /opt/dokuwiki
      a2_directories:
        - name: /
          options:
            - Options FollowSymLinks
            - AllowOverride None
            - Require all denied
        - name: /opt/wordpress
          options:
              - Options FollowSymLinks MultiViews Includes ExecCGI
              - AllowOverride all
              - Order allow,deny
              - Allow from all
              - Require all granted
        - name: /opt/dokuwiki
          options:
            - Options Indexes FollowSymLinks MultiViews
            - AllowOverride none
            - Order allow,deny
            - allow from all
            - Require all granted
      a2_locationmatches:
        - name: "/(data|conf|bin|inc)/"
          options:
            - Order allow,deny
            - Deny from all
            - Satisfy All
      a2modules_active:
        - 'rewrite'
      # mysql vars
      mysql_root_db_pass: OnlyUsedInVagrantDemo
      mysql_dbs:
        - wp_fireforms
      mysql_users:
        - name: wp_fireforms
          db: wp_fireforms
          pass: OnlyUsedInVagrant
          priv: "wp_fireforms.*:ALL"
      # Wordpress Vars
      wp_db_user: wp_fireforms
      wp_dir: /opt/wordpress
      wp_db_name: wp_fireforms
      wp_db_pass: OnlyUsedInVagrant
      wp_db_user: wp_fireforms
      wp_title: "Henrico Division of Fire"
      wp_url: http://192.168.33.10/blog
      wp_admin: wp_fireadmin
      wp_admin_pw: DemoPasswordOnly
      wp_admin_email: set@inplaybook.com
      wp_plugins:
        - ninja-forms
        - wpmandrill
      wp_themes:
        - wp-simple
      wp_theme_active: wp-simple
      # DokuWiki Vars
      dw_dir: /opt/dokuwiki
    roles:
      - common
      - php
      - apache2
      # - mysql
      # - wordpress
      # - dokuwiki
