---
  - hosts: all
    user: vagrant
    # sudo: yes
    vars_files:
      - vars/{{ ansible_os_family }}.yml
    vars:
      # Common vars
      playbook_name: utility-playbook
      ssh_users: None
      sudoers: None
      deleted_users: None
      # Apache vars
      a2_rules:
        - RewriteEngine on
        - "RewriteRule (.*) /opt/mediawiki/$1"
      a2_aliases:
        - name: /blog
          path: /opt/wordpress
        - name: /wiki
          path: /opt/mediawiki
      a2_directories:
        - name: /opt/wordpress
          options:
              - Options FollowSymLinks MultiViews Includes ExecCGI
              - AllowOverride all
              - Order allow,deny
              - Allow from all
              - Require all granted
        - name: /opt/mediawiki
          options:
              - Options +FollowSymLinks
              - AllowOverride All
              - Order allow,deny
              - Allow from all
        - name: /opt/mediawiki/config
          options:
            - "Options -FollowSymLinks"
            - AllowOverride None
            - "<IfModule mod_php5.c>"
            - "php_admin_flag engine off"
            - "</IfModule>"
        - name: /opt/mediawiki/images
          options:
            - "Options -FollowSymLinks"
            - AllowOverride None
            - "<IfModule mod_php5.c>"
            - "php_admin_flag engine off"
            - "</IfModule>"
        - name: /opt/mediawiki/upload
          options:
            - "Options -FollowSymLinks"
            - AllowOverride None
            - "<IfModule mod_php5.c>"
            - "php_admin_flag engine off"
            - "</IfModule>"
      a2modules_active:
        - 'rewrite'
      # mysql vars
      mysql_root_db_pass: OnlyUsedInVagrantDemo
      mysql_dbs:
        - wp_fireforms
        - wiki
      mysql_users:
        - name: wp_fireforms
          db: wp_fireforms
          pass: OnlyUsedInVagrant
          priv: "wp_fireforms.*:ALL"
        - name: wikiuser
          db: wiki
          pass: WikiInVagrantOnly
          priv: "wiki.*:ALL"
      # Wordpress Vars
      wp_db_user: wp_fireforms
      wp_dir: /opt/testpress
      wp_db_name: wp_fireforms
      wp_db_pass: OnlyUsedInVagrant
      wp_db_user: wp_fireforms
      wp_title: "Henrico Division of Fire"
      wp_url: http://192.168.33.10/
      wp_admin: wp_fireadmin
      wp_admin_pw: DemoPasswordOnly
      wp_admin_email: set@inplaybook.com
      wp_plugins:
        - ninja-forms
        - wpmandrill
      wp_themes:
        - wp-simple
      wp_theme_active: wp-simple
      # Mediawiki Vars
      mw_dir: /opt/mediawiki
      mw_site_name: "Division of Fire Wiki"
      mw_namespace: "Division_of_Fire_Wiki"
      mw_scriptpath: /wiki
      mw_server: http://192.168.33.10/mediawiki/
      mw_logo: /opt/mediawiki/images/HenricoSealShare.png
    roles:
      - common
      - apache2
      - mysql
      - php
      - wordpress
      - mediawiki
