# Install Mediawiki

- name: INSTALL | Install imagemagic via apt/get
  apt: pkg=imagemagick state=present
  tags: install

- name: INSTALL | Clone latest version of Mediawiki from GitHub
  tags: install
  git:
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/core.git
    dest: "{{ mw_dir }}"
    depth: 1
    update: no

- name: INSTALL | Install composer php dependency manager
  command: "curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer"

- name: CONFIGURE | Determin if composer lock file exists
  stat: "{{ mw_dir }}/composer.lock"
  register: composer_lock

- name: INSTALL | Execute composer for php dependencies
  command: "composer install --no-dev"
  when: composer_lock.exists == False

- name: UPDATE | Update composer php dependencies
  command: "composer update --no-dev"
  when: composer_lock.exists == True

# Security Config
- name: SECURITY | Change owner of wp directory to apache user.
  tags: security
  file:
    path: "{{ mw_dir }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: www-data
    group: www-data
