# Install Mediawiki

- name: INSTALL | Install imagemagic via apt/get
  apt: pkg=imagemagick state=present
  tags: install



- name: INSTALL | Clone latest version of Mediawiki from GitHub
  tags: install
  git:
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/core.git
    dest: "{{ mw_dir }}"
    depth: 1
    update: no

- name: INSTALL | Create LocalSettings.php file in root
  tags: install
  template:
    src: LocalSettings.php.j2
    dest: "{{ mw_dir }}/LocalSettings.php"
    mode: 0600
    group: root
    owner: root

# Add Henrico Seal
- name: CONFIGURE | Add logo
  copy:
    src: "../../../files/HenricoSealShare.png"
    dest: "{{ mw_dir }}/images/HenricoSealShare.png"
    mode: 0755

# Security Config
- name: SECURITY | Change owner of wp directory to apache user.
  tags: security
  file:
    path: "{{ mw_dir }}"
    state: directory
    mode: 0755
    recurse: yes
    owner: www-data
    group: www-data


# Config Apache
# - name: APACHE | Setup apache vhost for site
#   tags: apache
#   template:
#     src: vhost.conf.j2
#     dest: "/etc/apache2/sites-available/{{ mw_db_name }}.conf"
#     mode: 0644
#
# - name: APACHE | Deactivate default site
#   tags: apache
#   sudo: yes
#   command: "a2dissite 000-default"
#
# - name: APACHE | Activate wordpress site
#   tags: apache
#   sudo: yes
#   command: "a2ensite {{ mw_db_name }}"
#   notify: restart apache
