---
  - include: RedHat.yml
    when: ansible_os_family == 'RedHat'

  - include: Debian.yml
    when: ansible_os_family == 'Debian'
    
  - name: INSTALL | Determining if wiki already exists
    stat: path="{{ dw_dir }}"
    register: dw_install

  - include: install-dokuwiki.yml
    when: dw_install.stat.exists == False

  - name: CONFIG | own all files to the webapp
    file:
      path: "{{ dw_dir }}"
      state: directory
      recurse: yes
      owner: "{{ dw_app_user }}"
      group: "{{ dw_app_group }}"
