---
  - name: DEPS | Installing system dependencies.
    apt: pkg={{ item }} state=present
    with_items:
      - imagemagick
      - unzip
      - gzip

  - name: INSTALL | Determining if wiki already exists
    stat: path="{{ dw_dir }}"
    register: dw_install

  - name: INSTALL | download latest stable build
    get_url:
      url: http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
      dest: "{{ dw_tempdir }}/dokuwiki-stable.tgz"
    when: dw_install.stat.exists == False

  - name: INSTALL | extract stable build to destination
    unarchive:
      src:  "{{ dw_tempdir }}/dokuwiki-stable.tgz"
      dest: /opt
    when: dw_install.stat.exists == False

  - name: CONFIG | own all files to the webapp
    file:
      path: "{{ dw_dir }}"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
