---
  - name: INSTALL | openssl
    yum: name=openssl state=present

  - include: RedHat.yml
    when: ansible_os_family == 'RedHat'

  - name: SSL | Copy ssl pem file
    copy:
      src: {{ https_pem }}
      dest: {{ https_pem_path }}
      owner: root
      group: root
      mode: 400
    when: https_pem is defined and https_pem_path is defined

  - name: SSL | Copy ssl key file
    copy:
      src: {{ https_key }}
      dest: {{ https_key_path }}
      owner: root
      group: root
      mode: 400
    when: https_key is defined and https_key_file is defined

  - name: CONFIG | generate apache site config
    template:
      src: ssl.config.j2
      dest: "{{ apache_sites_dir }}/{{ https_siteconfig }}.conf"
      mode: 0644
    notify:
      - restart apache
