---
- apt: pkg=apache2 state=installed
  when: ansible_os_family == 'Debian'

- yum: name=httpd state=installed
  when: ansible_os_family == 'RedHat'

- name: Apache | Enable modules
  apache2_module: name={{ item }} state=present
  tags: apache2
  when: ansible_os_family == 'Debian' and a2modules_active
  with_items: "{{ a2modules_active }}"
  notify:
    - restart apache

- name: Apache | Disable modules
  apache2_module: name={{ item }} state=absent
  tags: apache2
  when: ansible_os_family == 'Debian' a2modules_inactive
  with_items: "{{ a2modules_inactive }}"
  notify:
    - restart apache
