---
  - name: YUM | install apache2 packages
    yum: name={{ item }} state=installed
    with_items: apache_pkgs

    # for some reason enable is not working doing it manually and with enable
  - name: ENABLE | allowing apache to start on boot
    command: chkconfig httpd on
    notify:
      - enable apache

  # Required on CentOS - not enabled on our RHEL images for some reason.
  # - name: FIREWALL | open http service port
  #   firewalld: service=http permanent=true state=enabled
  #
  # - service: name=firewalld state=restarted
