# see https://github.com/bertvv/ansible-role-mariadb/blob/master/tasks/main.yml
---
  - name: CONFIGURE | load variables for distro
    include_vars: "{{ ansible_os_family}}.yml"

  - name: INSTALL | APT packages
    apt: pkg={{ item }} state=installed update_cache=yes
    with_items: "{{ mysql_pkgs }}"
    when: ansible_os_family == 'Debian'

  - name: INSTALL | YUM packages
    yum: name={{ item }} state=installed
    with_items: "{{ mysql_pkgs }}"
    when: ansible_os_family == 'RedHat'

  - name: CONFIGURE directory /etc/mysql/conf.d created
    file: path=/etc/mysql/conf.d state=directory
    notify:
     - restart mysql

  - name:  CONFIGURE | start and enable mysql on RedHat
    service: name={{ mysql_service }} state=started enabled=yes
    when: ansible_os_family == 'RedHat'

  - name: SECURITY | update mysql root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
    with_items:
     - 127.0.0.1
     - ::1
     - localhost
    when: ansible_hostname != 'localhost'

# NOTE these MUST come after the pw reset above.
  - name: CONFIGURE | copy central mysql my.cnf file
    template:
      src: "my.cnf.{{ ansible_os_family }}.j2"
      dest: "{{ mysql_conf_dir}}/my.cnf"

  - name: CONFIGURE | copy .my.cnf with root password to ansible user
    template: src=my.cnf.j2 dest=~/.my.cnf mode=0600
    notify:
      - restart mysql

  - name: SECURITY | remove all anonymous MySQL Users
    mysql_user: name='' host={{ item }} state=absent
    with_items:
      - localhost

  - name: SECURITY remove the default test DB
    mysql_db: name=test state=absent

  - name: DATABASE | create databases
    mysql_db: name={{ item }} state=present
    with_items: mysql_dbs

  - name: DATABASE | create database users
    mysql_user:
      name: "{{ item.name }}"
      password: "{{ item.pass }}"
      priv: "{{ item.priv }}"
      state: present
      host: "{{ item.host | default('localhost') }}"
    with_items: mysql_users
